# Basic Information
title: Tak Wa Ng
position: Postdoctoral Fellow
affiliation: Department of Statistics and Actuarial Science, University of Hong Kong
email: takwang (at) hku.hk

# Search Engine Optimization (SEO)
keywords: "Tak Wa Ng, Actuarial Science, Financial Mathematics, HKU"
description: "Personal homepage of Tak Wa Ng, Postdoctoral Fellow at HKU."
canonical: https://ngtakwa.github.io/

# Links
google_scholar: https://scholar.google.com/citations?user=OmgMLTUAAAAJ&hl=en&oi=ao
github_link: https://github.com/ngtakwa
linkedin: https://www.linkedin.com/in/tak-wa-ng-5273a7218/

# Images
avatar: "assets/img/avatar.png"
favicon: "assets/img/favicon.png"
favicon_dark: "assets/img/favicon-dark.png"

# Footnote
enable_footnote: true

# Auto Dark Mode
auto_dark_mode: true

# Font
font: "Serif"

# Remote Theme
remote_theme: yaoyao-liu/minimal-light

# Exclude Files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
